Document: hello-dhmake
Title: Debian hello-dhmake Manual
Author: <insert document author here>
Abstract: This manual describes what hello-dhmake is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hello-dhmake/hello-dhmake.sgml.gz

Format: postscript
Files: /usr/share/doc/hello-dhmake/hello-dhmake.ps.gz

Format: text
Files: /usr/share/doc/hello-dhmake/hello-dhmake.text.gz

Format: HTML
Index: /usr/share/doc/hello-dhmake/html/index.html
Files: /usr/share/doc/hello-dhmake/html/*.html
